### ISSUE TITLE
Unable to use this action with IAM user authentication

### ISSUE THREAD

**Issue by Catskan** [aws-actions/aws-secretsmanager-get-secrets#101]
Hi everyone,

I have to get secrets values from my AWS SecretsManager but seems this actions doesn't works as expected with IAM user authentication.

So, I authenticate over AWS with a dedicated IAM Role and the auth working good. 
This authentication works with my terraform steps for example.

But, the `aws-actions/aws-secretsmanager-get-secrets` seems not working with this authentication method because it doesn't use the right IAM Role.

Outputs :
```
Run aws-actions/configure-aws-credentials@v4
  with:
    aws-region: eu-west-3
    output-credentials: true
    audience: sts.amazonaws.com
Proceeding with IAM user credentials
Run aws-actions/aws-secretsmanager-get-secrets@v2
  with:
    secret-ids: project/my-secret
    parse-json-secrets: true
  env:
    AWS_DEFAULT_REGION: eu-west-3
    AWS_REGION: eu-west-3
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
    AWS_SESSION_TOKEN: 
Building secrets list...
Your secret names may be transformed in order to be valid environment variables (see README). Enable Debug logging in order to view the new environment names.
Error: Failed to fetch secret: 'dpfv2/snowflake_dbt_users-20240329094341248700000001'. Error: AccessDeniedException: User: arn:aws:sts::822365211807:assumed-role/github-action-eks-node-group-20240321170827804400000001/i-0462d11c5e899cd8c is not authorized to perform: secretsmanager:GetSecretValue on resource: dpfv2/snowflake_dbt_users-20240329094341248700000001 because no identity-based policy allows the secretsmanager:GetSecretValue action.
Completed adding secrets.
```

Github Action code
```
    - name: Configure AWS credentials
      id: aws_creds
      if: |
        github.job != 'tests' &&
        (inputs.setup_docker == 'true' || inputs.setup_release == 'true' || inputs.setup_aws == 'true')
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: '${{ inputs.aws_access_key_id }}'
        aws-secret-access-key: '${{ inputs.aws_secret_access_key }}'
        aws-region: '${{ inputs.aws_region }}'
        output-credentials: true

    - name: Get Snowflake DBT Secrets
      id: get-secrets
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: project/my-secret
        parse-json-secrets: true
      env:
        AWS_ACCESS_KEY_ID: '${{ inputs.aws_access_key_id }}'
        AWS_SECRET_ACCESS_KEY: '${{ inputs.aws_secret_access_key }}'
        AWS_SESSION_TOKEN: '${{ steps.aws_creds.outputs.aws-session-token}}'
```
As you can saw, I also tried to add `AWS_` environment variables but seems not supported.
The secretmanager actions want to use the role used by our self-hosted-runner, instead of our dedicated AWS user used for our CI (ci_project).

This actions should works with this authentication method ?

Thanks in advance for your advice.

Bests

Catskan
