### ISSUE TITLE
Parsing json secrets without prefix

### ISSUE THREAD

**Issue by davenix-palmetto** [aws-actions/aws-secretsmanager-get-secrets#11]
Hello all. Would it be possible to parse a json secret and inject the keys as environment variables raw into the environment? For our purposes this would be a cleaner solution than having to account for the variables with the added prefix. 

Thanks in advance for any and all thoughts in this regard!

**Comment by skeggse** [comment]
Along these lines, it'd be nice to be able to extract a specific key from a JSON secret, and assign it to a specific environment variable name without the name being coupled to the keys in the JSON secret.

**Comment by jromero-pg** [comment]
Hi @ixwishes,

We needed this feature to migrate from [say8425/aws-secrets-manager-actions](https://github.com/say8425/aws-secrets-manager-actions). 

I've put up a [PR](https://github.com/aws-actions/aws-secretsmanager-get-secrets/pull/16) to introduce this feature as part of "custom prefixing". Please take a look. I'm happy to resolve any questions/comments/concerns to get it merged.

We'd hate to have a bespoke version of this action.

**Comment by goyalya** [comment]
Closing this and tracking it [here](https://github.com/aws-actions/aws-secretsmanager-get-secrets/pull/16)

**Comment by FalconerTC** [comment]
Being able to extract specific keys from JSON would be really useful

**Comment by akremer** [comment]
+1. This feature is necessary for our use case as well.

**Comment by shftlvch** [comment]
+1, would save a lot of time for custom scripting

We use prefixes for secrets like `prod/*` and `dev/*`. With the current solution, it's PROD_* and DEV_* env variables which don't make sense.

**Comment by tripodsan** [comment]
FWIW, I added this to unprefix them:

```yaml
      - name: Fetch AWS Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          parse-json-secrets: true
          secret-ids: |
            /project/github-action-secrets
      - name: unprefix variables
        run: |
          for variable in "${!_PROJECT_GITHUB_ACTION_SECRETS_@}"; do 
            echo "${variable#_PROJECT_GITHUB_ACTION_SECRETS_}=${!variable}" >> $GITHUB_ENV
          done
```
