### ISSUE TITLE
aws-secretsmanager-get-secrets@v2 using node 20 instead of node 16

### ISSUE THREAD

**Issue by dpakpdl** [aws-actions/aws-secretsmanager-get-secrets#161]
Running on with github runners and we're running into issues where @V2 is using node20 instead of node16.

Steps:

1. Run aws-actions/aws-secretsmanager-get-secrets@v2
```/home/ec2-user/actions-runner/externals/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/ec2-user/actions-runner/externals/node20/bin/node)
/home/ec2-user/actions-runner/externals/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/ec2-user/actions-runner/externals/node20/bin/node)```

I added `ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true` in the env but the same issues persists. The following is my action file.

```
name: Test-Deploy

on:
    workflow_dispatch:

env:
    ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
    Docker_Image_Build_Deploy:
        runs-on: backend
        steps:
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Get Secrets from AWS Secrets Manager
              id: get-secrets
              uses: aws-actions/aws-secretsmanager-get-secrets@v2
              with:
                  secret-ids: REDIS_PASSWORD
```
