### ISSUE TITLE
can you please add the ability to inject the secrets region ?

### ISSUE THREAD

**Issue by chkp-dvirpa** [aws-actions/aws-secretsmanager-get-secrets#166]
like so
```yaml
- name: get secret 
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        region: eu-west-1
        secret-ids: |
          secret_name
        parse-json-secrets: true
```
