### ISSUE TITLE
particular json secret failing to parse

### ISSUE THREAD

**Issue by kaykhan** [aws-actions/aws-secretsmanager-get-secrets#18]
We are attempting to migrate our github ci from using https://github.com/marketplace/actions/aws-secrets-manager-action to **this** action.

However we are finding for a particular secret it is failing to parse and we are unsure why.

```
env:
  CI: true
  ACTIONS_RUNNER_DEBUG: true
  
...

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-2
    - name: Read AWS Secret Manager
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-ids: |
          prod-elastic
          prod-rds
        parse-json-secrets: true
...

    - name: deploy
      working-directory: example-lambda
      run: |    
        npm i -g serverless
        npm install 
        serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
        sls deploy --stage production
      env:
        DATABASE_HOST: ${{ env.PROD_RDS_MASTER_HOST }}
        DATABASE_USERNAME: ${{ env.PROD_RDS_MYSQL_USERNAME }}
        DATABASE_PASSWORD: ${{ env.PROD_RDS_MYSQL_PASSWORD }}
        DATABASE_NAME: ${{ env.PROD_RDS_DATABASE_NAME }}
        FUNCTIONBEAT_SUBSCRIPTION_STREAM: ${{ env.PROD_ELASTIC_FUNCTIONBEAT_SUBSCRIPTION_STREAM }}       
        FUNCTIONBEAT_SUBSCRIPTION_ROLE: ${{ env.PROD_ELASTIC_FUNCTIONBEAT_SUBSCRIPTION_ROLE }}                 

```

prod-rds successfully parses. 

**however prod-elastic fails to parse. Why is this happening**

**content of secret:**
![image](https://user-images.githubusercontent.com/5202527/228198712-ad32c74b-884f-4319-8e95-4e75e5423efd.png)

note: the previous action we have been using successfully parses this secret (prod-elastic)

Attempted to enable debugging `ACTIONS_RUNNER_DEBUG` however we don't see any extra information displayed in the step.

**Comment by zpbonjour** [comment]
@kaykhan What was your solution here?

**Comment by kaykhan** [comment]
> @kaykhan What was your solution here?

Hey can't remember specifically what the problem was here but we do have this working. Here is an example

```
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-2
  
  deploy:
    needs: unit-test
    name: deploy
    if: startsWith(github.ref, 'refs/tags/')
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-2
      - name: Read AWS Secret Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            prod-rds
            prod-elastic
          parse-json-secrets: true
      - name: deploy
        run: |
          npm i -g serverless
          npm install 
          serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
          sls deploy --stage production
        env:
          DATABASE_HOST: ${{ env.PROD_RDS_MASTER_HOST }}
          DATABASE_USERNAME: ${{ env.PROD_RDS_MYSQL_SOME_USERNAME }}
          DATABASE_PASSWORD: ${{ env.PROD_RDS_MYSQL_SOME_PASSWORD }}
          DATABASE_NAME: ${{ env.PROD_RDS_DATABASE_NAME }}
```

I think in the past we had some issues with this env var/val `CI: true` if you have that try removing it. Other than that i dont know.
