### ISSUE TITLE
Using secret-ids with parse-json-secrets and properties starting with a number can end up with double-underscores

### ISSUE THREAD

**Issue by fdx-wayne-yeap** [aws-actions/aws-secretsmanager-get-secrets#238]
When using something like:

```yaml
  - uses: aws-actions/configure-aws-credentials@v4
    with:
    secret-ids: |
      PREFIX, secret-name
    parse-json-secrets: true
```

and the JSON inside the secret starts with a number, e.g. `{ "1property": "value" }`, the generated environment variable will end up being:
`PREFIX__1PROPERTY="value"` with two underscores.

I wold have expected `PREFIX_1PROPERTY` because it's no longer an invalid environment variable that starts with a number when we have a prefix.

Not sure how to go about fixing this because I assume people encountering this bug will have noticed this odd behavior and worked around it, as I have!
